// type definitions for Cypress object "cy"
// <reference types="cypress" />

describe("Faz uma requisição http", function () {
  beforeEach(() => {
    cy.visitFilled();
  });

  it("Faz uma requisição HTTP", () => {
    cy.request(
      "https://cac-tat.s3.eu-central-1.amazonaws.com/index.html"
    ).should((response) => {
      const { status, statusText, body } = response;
      expect(status).to.equal(200);
      expect(statusText).to.equal("OK");
      expect(body).to.include("CAC TAT");
    });
  });
});
